
INSERT INTO `language` VALUES (3270,'es','admin-areacodes','Códigos de Area',1,'2016-06-16 15:05:27'),(3278,'en','admin-areacodes','Area Codes',1,'2016-06-16 15:58:37');

INSERT INTO `language` VALUES (3266,'es','answered_calls_by_state','Atendidas por Estado',0,'2016-06-15 22:17:29'),(3271,'es','unanswered_calls_by_state','No Atendidas por Estado',0,'2016-06-16 15:09:09'),(3273,'es','distribution_by_state','Distribución por Estado',0,'2016-06-16 15:51:32'),(3275,'en','distribution_by_state','Distribution by State',0,'2016-06-16 15:58:37'),(3276,'en','answered_calls_by_state','Answered by State',0,'2016-06-16 15:58:37'),(3277,'en','unanswered_calls_by_state','Unanswered by State',0,'2016-06-16 15:58:37');

REPLACE INTO designer (keyword,parameter,value) VALUES ('setup_reports','','admin-setup.php,admin-designer.php,admin-users.php,admin-acl.php,admin-language.php,admin-schedule.php,admin-queuegroups.php,admin-areacodes.php');

REPLACE INTO designer (keyword,parameter,value) VALUES ('answered_reports','','answered_calls_summary.php,answered_calls_by_holdtime.php,answered_calls_by_queue.php,answered_calls_by_agent.php,answered_calls_by_event.php,answered_calls_by_url.php,answered_calls_by_did.php,answered_calls_by_duration.php,answered_calls_transferred.php,answered_calls_by_state.php,answered_calls_detail.php');

REPLACE INTO designer (keyword,parameter,value) VALUES ('unanswered_reports','','unanswered_calls_summary.php,unanswered_calls_by_holdtime.php,unanswered_calls_by_event.php,unanswered_calls_by_queue.php,unanswered_calls_by_url.php,unanswered_calls_by_did.php,unanswered_calls_by_state.php,unanswered_calls_detail.php');

REPLACE INTO designer (keyword,parameter,value) VALUES ('distribution_reports','','distribution_summary.php,distribution_by_queue.php,distribution_by_month.php,distribution_by_week.php,distribution_by_day.php,distribution_by_hour.php,distribution_by_day_of_week.php,distribution_by_url.php,distribution_by_did.php,distribution_by_agent.php,distribution_by_state.php,distribution_detail.php');

REPLACE INTO designer (keyword,parameter,value) VALUES ('JOIN_TABLE','name as State','LEFT JOIN area_codes ON SUBSTRING(SUBSTRING(clid,-10),1,3)=code');
REPLACE INTO designer (keyword,parameter,value) VALUES ('JOIN_TABLE','name as State','LEFT JOIN area_codes ON SUBSTRING(SUBSTRING(q2.info2,-10),1,3)=code');
REPLACE INTO designer (keyword,parameter,value) VALUES ('COLUMN_ANSWERED','State','CUSTOM_STATE');
REPLACE INTO designer (keyword,parameter,value) VALUES ('ANSWERED_DISPLAY_ROWS','State','Received,Completed,Transferred,%% Calls,Talk Time,%% Talk Time,Avg Talk Time,Ring Time,Wait Time,Avg Wait Time,Max Wait Time');

DROP TABLE IF EXISTS `area_codes`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `area_codes` (
  `id` int(11) NOT NULL auto_increment,
  `code` int(11) NOT NULL,
  `name` varchar(100) default NULL,
  `state` char(10) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=747 DEFAULT CHARSET=utf8;
SET character_set_client = @saved_cs_client;

--
-- Dumping data for table `area_codes`
--

LOCK TABLES `area_codes` WRITE;
/*!40000 ALTER TABLE `area_codes` DISABLE KEYS */;
INSERT INTO `area_codes` VALUES (1,201,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (2,202,'Washington D.C.','US-DC');
INSERT INTO `area_codes` VALUES (3,203,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (4,204,'Canada - Manitoba',NULL);
INSERT INTO `area_codes` VALUES (5,205,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (6,206,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (7,207,'Maine','US-ME');
INSERT INTO `area_codes` VALUES (8,208,'Idaho','US-ID');
INSERT INTO `area_codes` VALUES (9,209,'California','US-CA');
INSERT INTO `area_codes` VALUES (10,210,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (11,212,'New York','US-NY');
INSERT INTO `area_codes` VALUES (12,213,'California','US-CA');
INSERT INTO `area_codes` VALUES (13,214,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (14,215,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (15,216,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (16,217,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (17,218,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (18,219,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (19,220,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (20,224,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (21,225,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (22,226,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (23,228,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (24,229,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (25,231,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (26,234,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (27,236,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (28,239,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (29,240,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (30,242,'Bahamas',NULL);
INSERT INTO `area_codes` VALUES (31,246,'Barbados',NULL);
INSERT INTO `area_codes` VALUES (32,248,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (33,249,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (34,250,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (35,251,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (36,252,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (37,253,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (38,254,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (39,256,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (40,260,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (41,262,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (42,264,'Anguilla',NULL);
INSERT INTO `area_codes` VALUES (43,267,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (44,268,'Antigua & Barbuda',NULL);
INSERT INTO `area_codes` VALUES (45,269,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (46,270,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (47,272,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (48,276,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (49,281,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (50,284,'British Virgin Islands',NULL);
INSERT INTO `area_codes` VALUES (51,289,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (52,301,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (53,302,'Delaware','US-DL');
INSERT INTO `area_codes` VALUES (54,303,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (55,304,'West Virginia','US-WV');
INSERT INTO `area_codes` VALUES (56,305,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (57,306,'Canada - Saskatchewan',NULL);
INSERT INTO `area_codes` VALUES (58,307,'Wyoming','US-WY');
INSERT INTO `area_codes` VALUES (59,308,'Nebraska','US-NE');
INSERT INTO `area_codes` VALUES (60,309,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (61,310,'California','US-CA');
INSERT INTO `area_codes` VALUES (62,312,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (63,313,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (64,314,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (65,315,'New York','US-NY');
INSERT INTO `area_codes` VALUES (66,316,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (67,317,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (68,318,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (69,319,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (70,320,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (71,321,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (72,323,'California','US-CA');
INSERT INTO `area_codes` VALUES (73,325,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (74,330,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (75,331,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (76,334,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (77,336,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (78,337,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (79,339,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (80,340,'US Virgin Islands','US-VI');
INSERT INTO `area_codes` VALUES (81,343,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (82,345,'Cayman Islands',NULL);
INSERT INTO `area_codes` VALUES (83,346,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (84,347,'New York','US-NY');
INSERT INTO `area_codes` VALUES (85,351,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (86,352,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (87,360,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (88,361,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (89,364,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (90,365,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (91,385,'Utah','US-UT');
INSERT INTO `area_codes` VALUES (92,386,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (93,401,'Rhode Island','US-RI');
INSERT INTO `area_codes` VALUES (94,402,'Nebraska','US-NE');
INSERT INTO `area_codes` VALUES (95,403,'Canada - Alberta',NULL);
INSERT INTO `area_codes` VALUES (96,404,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (97,405,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (98,406,'Montana','US-MT');
INSERT INTO `area_codes` VALUES (99,407,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (100,408,'California','US-CA');
INSERT INTO `area_codes` VALUES (101,409,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (102,410,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (103,412,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (104,413,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (105,414,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (106,415,'California','US-CA');
INSERT INTO `area_codes` VALUES (107,416,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (108,417,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (109,418,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (110,419,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (111,423,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (112,424,'California','US-CA');
INSERT INTO `area_codes` VALUES (113,425,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (114,430,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (115,431,'Canada - Manitoba',NULL);
INSERT INTO `area_codes` VALUES (116,432,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (117,434,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (118,435,'Utah','US-UT');
INSERT INTO `area_codes` VALUES (119,437,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (120,438,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (121,440,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (122,441,'Bermuda',NULL);
INSERT INTO `area_codes` VALUES (123,442,'California','US-CA');
INSERT INTO `area_codes` VALUES (124,443,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (125,450,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (126,456,'Carrier Services',NULL);
INSERT INTO `area_codes` VALUES (127,458,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (128,469,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (129,470,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (130,473,'Grenada',NULL);
INSERT INTO `area_codes` VALUES (131,475,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (132,478,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (133,479,'Arkansas','US-AR');
INSERT INTO `area_codes` VALUES (134,480,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (135,484,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (136,500,'Personal Communications Services',NULL);
INSERT INTO `area_codes` VALUES (137,501,'Arkansas','US-AR');
INSERT INTO `area_codes` VALUES (138,502,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (139,503,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (140,504,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (141,505,'New Mexico','US-NM');
INSERT INTO `area_codes` VALUES (142,506,'Canada - New Brunswick',NULL);
INSERT INTO `area_codes` VALUES (143,507,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (144,508,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (145,509,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (146,510,'California','US-CA');
INSERT INTO `area_codes` VALUES (147,512,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (148,513,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (149,514,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (150,515,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (151,516,'New York','US-NY');
INSERT INTO `area_codes` VALUES (152,517,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (153,518,'New York','US-NY');
INSERT INTO `area_codes` VALUES (154,519,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (155,520,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (156,530,'California','US-CA');
INSERT INTO `area_codes` VALUES (157,531,'Nebraska','US-NE');
INSERT INTO `area_codes` VALUES (158,534,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (159,539,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (160,540,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (161,541,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (162,551,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (163,559,'California','US-CA');
INSERT INTO `area_codes` VALUES (164,561,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (165,562,'California','US-CA');
INSERT INTO `area_codes` VALUES (166,563,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (167,567,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (168,570,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (169,571,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (170,573,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (171,574,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (172,575,'New Mexico','US-NM');
INSERT INTO `area_codes` VALUES (173,579,'Quebec',NULL);
INSERT INTO `area_codes` VALUES (174,580,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (175,581,'Quebec',NULL);
INSERT INTO `area_codes` VALUES (176,585,'New York','US-NY');
INSERT INTO `area_codes` VALUES (177,586,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (178,587,'Canada - Alberta',NULL);
INSERT INTO `area_codes` VALUES (179,600,'\"Canada only',NULL);
INSERT INTO `area_codes` VALUES (180,601,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (181,602,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (182,603,'New Hampshire','US-NH');
INSERT INTO `area_codes` VALUES (183,604,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (184,605,'South Dakota','US-SD');
INSERT INTO `area_codes` VALUES (185,606,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (186,607,'New York','US-NY');
INSERT INTO `area_codes` VALUES (187,608,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (188,609,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (189,610,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (190,612,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (191,613,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (192,614,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (193,615,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (194,616,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (195,617,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (196,618,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (197,619,'California','US-CA');
INSERT INTO `area_codes` VALUES (198,620,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (199,623,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (200,626,'California','US-CA');
INSERT INTO `area_codes` VALUES (201,628,'California','US-CA');
INSERT INTO `area_codes` VALUES (202,629,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (203,630,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (204,631,'New York','US-NY');
INSERT INTO `area_codes` VALUES (205,636,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (206,639,'Canada - Saskatchewan',NULL);
INSERT INTO `area_codes` VALUES (207,641,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (208,646,'New York','US-NY');
INSERT INTO `area_codes` VALUES (209,647,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (210,649,'Turks & Caicos',NULL);
INSERT INTO `area_codes` VALUES (211,650,'California','US-CA');
INSERT INTO `area_codes` VALUES (212,651,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (213,657,'California','US-CA');
INSERT INTO `area_codes` VALUES (214,660,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (215,661,'California','US-CA');
INSERT INTO `area_codes` VALUES (216,662,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (217,664,'Montserrat',NULL);
INSERT INTO `area_codes` VALUES (218,667,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (219,669,'California','US-CA');
INSERT INTO `area_codes` VALUES (220,670,'Northern Mariana Isl.',NULL);
INSERT INTO `area_codes` VALUES (221,671,'Guam','US-GU');
INSERT INTO `area_codes` VALUES (222,678,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (223,681,'West Virginia','US-WV');
INSERT INTO `area_codes` VALUES (224,682,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (225,684,'American Samoa','US-AS');
INSERT INTO `area_codes` VALUES (226,701,'North Dakota','US-ND');
INSERT INTO `area_codes` VALUES (227,702,'Nevada','US-NV');
INSERT INTO `area_codes` VALUES (228,703,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (229,704,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (230,705,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (231,706,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (232,707,'California','US-CA');
INSERT INTO `area_codes` VALUES (233,708,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (234,709,'Canada - Newfoundland',NULL);
INSERT INTO `area_codes` VALUES (235,712,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (236,713,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (237,714,'California','US-CA');
INSERT INTO `area_codes` VALUES (238,715,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (239,716,'New York','US-NY');
INSERT INTO `area_codes` VALUES (240,717,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (241,718,'New York','US-NY');
INSERT INTO `area_codes` VALUES (242,719,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (243,720,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (244,721,'Sint Maarten',NULL);
INSERT INTO `area_codes` VALUES (245,724,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (246,725,'Nevada','US-NV');
INSERT INTO `area_codes` VALUES (247,727,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (248,731,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (249,732,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (250,734,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (251,740,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (252,747,'California','US-CA');
INSERT INTO `area_codes` VALUES (253,754,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (254,757,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (255,760,'California','US-CA');
INSERT INTO `area_codes` VALUES (256,762,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (257,763,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (258,765,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (259,767,'Dominica',NULL);
INSERT INTO `area_codes` VALUES (260,769,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (261,770,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (262,772,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (263,773,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (264,774,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (265,775,'Nevada','US-NV');
INSERT INTO `area_codes` VALUES (266,778,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (267,779,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (268,780,'Canada - Alberta',NULL);
INSERT INTO `area_codes` VALUES (269,781,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (270,782,'Canada - Nova Scotia/PEI',NULL);
INSERT INTO `area_codes` VALUES (271,784,'St. Vincent and the Grenadines',NULL);
INSERT INTO `area_codes` VALUES (272,785,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (273,786,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (274,787,'Puerto Rico','US-PR');
INSERT INTO `area_codes` VALUES (275,800,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (276,801,'Utah','US-UT');
INSERT INTO `area_codes` VALUES (277,802,'Vermont','US-VT');
INSERT INTO `area_codes` VALUES (278,803,'South Carolina','US-SC');
INSERT INTO `area_codes` VALUES (279,804,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (280,805,'California','US-CA');
INSERT INTO `area_codes` VALUES (281,806,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (282,807,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (283,808,'Hawaii','US-HI');
INSERT INTO `area_codes` VALUES (284,809,'Dominican Republic',NULL);
INSERT INTO `area_codes` VALUES (285,810,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (286,812,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (287,813,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (288,814,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (289,815,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (290,816,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (291,817,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (292,818,'California','US-CA');
INSERT INTO `area_codes` VALUES (293,819,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (294,828,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (295,829,'Dominican Republic',NULL);
INSERT INTO `area_codes` VALUES (296,830,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (297,831,'California','US-CA');
INSERT INTO `area_codes` VALUES (298,832,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (299,843,'South Carolina','US-SC');
INSERT INTO `area_codes` VALUES (300,844,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (301,845,'New York','US-NY');
INSERT INTO `area_codes` VALUES (302,847,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (303,848,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (304,849,'Dominican Republic',NULL);
INSERT INTO `area_codes` VALUES (305,850,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (306,855,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (307,856,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (308,857,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (309,858,'California','US-CA');
INSERT INTO `area_codes` VALUES (310,859,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (311,860,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (312,862,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (313,863,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (314,864,'South Carolina','US-SC');
INSERT INTO `area_codes` VALUES (315,865,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (316,866,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (317,867,'\"Canada - NW Territories',NULL);
INSERT INTO `area_codes` VALUES (318,868,'Trinidad & Tobago',NULL);
INSERT INTO `area_codes` VALUES (319,869,'St. Kitts & Nevis',NULL);
INSERT INTO `area_codes` VALUES (320,870,'Arkansas','US-AR');
INSERT INTO `area_codes` VALUES (321,872,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (322,873,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (323,876,'Jamaica',NULL);
INSERT INTO `area_codes` VALUES (324,877,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (325,878,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (326,888,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (327,901,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (328,902,'Canada - Nova Scotia/PEI',NULL);
INSERT INTO `area_codes` VALUES (329,903,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (330,904,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (331,905,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (332,906,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (333,907,'Alaska','US-AK');
INSERT INTO `area_codes` VALUES (334,908,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (335,909,'California','US-CA');
INSERT INTO `area_codes` VALUES (336,910,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (337,912,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (338,913,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (339,914,'New York','US-NY');
INSERT INTO `area_codes` VALUES (340,915,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (341,916,'California','US-CA');
INSERT INTO `area_codes` VALUES (342,917,'New York','US-NY');
INSERT INTO `area_codes` VALUES (343,918,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (344,919,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (345,920,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (346,925,'California','US-CA');
INSERT INTO `area_codes` VALUES (347,928,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (348,929,'New York','US-NY');
INSERT INTO `area_codes` VALUES (349,930,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (350,931,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (351,936,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (352,937,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (353,938,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (354,939,'Puerto Rico','US-PR');
INSERT INTO `area_codes` VALUES (355,940,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (356,941,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (357,947,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (358,949,'California','US-CA');
INSERT INTO `area_codes` VALUES (359,951,'California','US-CA');
INSERT INTO `area_codes` VALUES (360,952,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (361,954,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (362,956,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (363,959,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (364,970,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (365,971,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (366,972,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (367,973,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (368,978,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (369,979,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (370,980,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (371,984,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (372,985,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (373,989,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (374,1201,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (375,1202,'Washington D.C.','US-DC');
INSERT INTO `area_codes` VALUES (376,1203,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (377,1204,'Canada - Manitoba',NULL);
INSERT INTO `area_codes` VALUES (378,1205,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (379,1206,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (380,1207,'Maine','US-ME');
INSERT INTO `area_codes` VALUES (381,1208,'Idaho','US-ID');
INSERT INTO `area_codes` VALUES (382,1209,'California','US-CA');
INSERT INTO `area_codes` VALUES (383,1210,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (384,1212,'New York','US-NY');
INSERT INTO `area_codes` VALUES (385,1213,'California','US-CA');
INSERT INTO `area_codes` VALUES (386,1214,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (387,1215,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (388,1216,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (389,1217,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (390,1218,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (391,1219,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (392,1220,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (393,1224,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (394,1225,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (395,1226,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (396,1228,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (397,1229,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (398,1231,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (399,1234,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (400,1236,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (401,1239,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (402,1240,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (403,1242,'Bahamas',NULL);
INSERT INTO `area_codes` VALUES (404,1246,'Barbados',NULL);
INSERT INTO `area_codes` VALUES (405,1248,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (406,1249,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (407,1250,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (408,1251,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (409,1252,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (410,1253,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (411,1254,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (412,1256,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (413,1260,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (414,1262,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (415,1264,'Anguilla',NULL);
INSERT INTO `area_codes` VALUES (416,1267,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (417,1268,'Antigua & Barbuda',NULL);
INSERT INTO `area_codes` VALUES (418,1269,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (419,1270,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (420,1272,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (421,1276,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (422,1281,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (423,1284,'British Virgin Islands',NULL);
INSERT INTO `area_codes` VALUES (424,1289,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (425,1301,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (426,1302,'Delaware','US-DL');
INSERT INTO `area_codes` VALUES (427,1303,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (428,1304,'West Virginia','US-WV');
INSERT INTO `area_codes` VALUES (429,1305,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (430,1306,'Canada - Saskatchewan',NULL);
INSERT INTO `area_codes` VALUES (431,1307,'Wyoming','US-WY');
INSERT INTO `area_codes` VALUES (432,1308,'Nebraska','US-NE');
INSERT INTO `area_codes` VALUES (433,1309,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (434,1310,'California','US-CA');
INSERT INTO `area_codes` VALUES (435,1312,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (436,1313,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (437,1314,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (438,1315,'New York','US-NY');
INSERT INTO `area_codes` VALUES (439,1316,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (440,1317,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (441,1318,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (442,1319,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (443,1320,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (444,1321,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (445,1323,'California','US-CA');
INSERT INTO `area_codes` VALUES (446,1325,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (447,1330,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (448,1331,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (449,1334,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (450,1336,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (451,1337,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (452,1339,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (453,1340,'US Virgin Islands','US-VI');
INSERT INTO `area_codes` VALUES (454,1343,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (455,1345,'Cayman Islands',NULL);
INSERT INTO `area_codes` VALUES (456,1346,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (457,1347,'New York','US-NY');
INSERT INTO `area_codes` VALUES (458,1351,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (459,1352,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (460,1360,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (461,1361,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (462,1364,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (463,1365,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (464,1385,'Utah','US-UT');
INSERT INTO `area_codes` VALUES (465,1386,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (466,1401,'Rhode Island','US-RI');
INSERT INTO `area_codes` VALUES (467,1402,'Nebraska','US-NE');
INSERT INTO `area_codes` VALUES (468,1403,'Canada - Alberta',NULL);
INSERT INTO `area_codes` VALUES (469,1404,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (470,1405,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (471,1406,'Montana','US-MT');
INSERT INTO `area_codes` VALUES (472,1407,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (473,1408,'California','US-CA');
INSERT INTO `area_codes` VALUES (474,1409,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (475,1410,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (476,1412,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (477,1413,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (478,1414,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (479,1415,'California','US-CA');
INSERT INTO `area_codes` VALUES (480,1416,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (481,1417,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (482,1418,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (483,1419,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (484,1423,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (485,1424,'California','US-CA');
INSERT INTO `area_codes` VALUES (486,1425,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (487,1430,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (488,1431,'Canada - Manitoba',NULL);
INSERT INTO `area_codes` VALUES (489,1432,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (490,1434,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (491,1435,'Utah','US-UT');
INSERT INTO `area_codes` VALUES (492,1437,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (493,1438,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (494,1440,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (495,1441,'Bermuda',NULL);
INSERT INTO `area_codes` VALUES (496,1442,'California','US-CA');
INSERT INTO `area_codes` VALUES (497,1443,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (498,1450,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (499,1456,'Carrier Services',NULL);
INSERT INTO `area_codes` VALUES (500,1458,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (501,1469,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (502,1470,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (503,1473,'Grenada',NULL);
INSERT INTO `area_codes` VALUES (504,1475,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (505,1478,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (506,1479,'Arkansas','US-AR');
INSERT INTO `area_codes` VALUES (507,1480,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (508,1484,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (509,1500,'Personal Communications Services',NULL);
INSERT INTO `area_codes` VALUES (510,1501,'Arkansas','US-AR');
INSERT INTO `area_codes` VALUES (511,1502,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (512,1503,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (513,1504,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (514,1505,'New Mexico','US-NM');
INSERT INTO `area_codes` VALUES (515,1506,'Canada - New Brunswick',NULL);
INSERT INTO `area_codes` VALUES (516,1507,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (517,1508,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (518,1509,'Washington','US-WA');
INSERT INTO `area_codes` VALUES (519,1510,'California','US-CA');
INSERT INTO `area_codes` VALUES (520,1512,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (521,1513,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (522,1514,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (523,1515,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (524,1516,'New York','US-NY');
INSERT INTO `area_codes` VALUES (525,1517,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (526,1518,'New York','US-NY');
INSERT INTO `area_codes` VALUES (527,1519,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (528,1520,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (529,1530,'California','US-CA');
INSERT INTO `area_codes` VALUES (530,1531,'Nebraska','US-NE');
INSERT INTO `area_codes` VALUES (531,1534,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (532,1539,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (533,1540,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (534,1541,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (535,1551,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (536,1559,'California','US-CA');
INSERT INTO `area_codes` VALUES (537,1561,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (538,1562,'California','US-CA');
INSERT INTO `area_codes` VALUES (539,1563,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (540,1567,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (541,1570,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (542,1571,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (543,1573,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (544,1574,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (545,1575,'New Mexico','US-NM');
INSERT INTO `area_codes` VALUES (546,1579,'Quebec',NULL);
INSERT INTO `area_codes` VALUES (547,1580,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (548,1581,'Quebec',NULL);
INSERT INTO `area_codes` VALUES (549,1585,'New York','US-NY');
INSERT INTO `area_codes` VALUES (550,1586,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (551,1587,'Canada - Alberta',NULL);
INSERT INTO `area_codes` VALUES (552,1600,'\"Canada only',NULL);
INSERT INTO `area_codes` VALUES (553,1601,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (554,1602,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (555,1603,'New Hampshire','US-NH');
INSERT INTO `area_codes` VALUES (556,1604,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (557,1605,'South Dakota','US-SD');
INSERT INTO `area_codes` VALUES (558,1606,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (559,1607,'New York','US-NY');
INSERT INTO `area_codes` VALUES (560,1608,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (561,1609,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (562,1610,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (563,1612,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (564,1613,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (565,1614,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (566,1615,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (567,1616,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (568,1617,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (569,1618,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (570,1619,'California','US-CA');
INSERT INTO `area_codes` VALUES (571,1620,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (572,1623,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (573,1626,'California','US-CA');
INSERT INTO `area_codes` VALUES (574,1628,'California','US-CA');
INSERT INTO `area_codes` VALUES (575,1629,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (576,1630,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (577,1631,'New York','US-NY');
INSERT INTO `area_codes` VALUES (578,1636,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (579,1639,'Canada - Saskatchewan',NULL);
INSERT INTO `area_codes` VALUES (580,1641,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (581,1646,'New York','US-NY');
INSERT INTO `area_codes` VALUES (582,1647,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (583,1649,'Turks & Caicos',NULL);
INSERT INTO `area_codes` VALUES (584,1650,'California','US-CA');
INSERT INTO `area_codes` VALUES (585,1651,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (586,1657,'California','US-CA');
INSERT INTO `area_codes` VALUES (587,1660,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (588,1661,'California','US-CA');
INSERT INTO `area_codes` VALUES (589,1662,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (590,1664,'Montserrat',NULL);
INSERT INTO `area_codes` VALUES (591,1667,'Maryland','US-MD');
INSERT INTO `area_codes` VALUES (592,1669,'California','US-CA');
INSERT INTO `area_codes` VALUES (593,1670,'Northern Mariana Isl.',NULL);
INSERT INTO `area_codes` VALUES (594,1671,'Guam','US-GU');
INSERT INTO `area_codes` VALUES (595,1678,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (596,1681,'West Virginia','US-WV');
INSERT INTO `area_codes` VALUES (597,1682,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (598,1684,'American Samoa','US-AS');
INSERT INTO `area_codes` VALUES (599,1701,'North Dakota','US-ND');
INSERT INTO `area_codes` VALUES (600,1702,'Nevada','US-NV');
INSERT INTO `area_codes` VALUES (601,1703,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (602,1704,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (603,1705,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (604,1706,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (605,1707,'California','US-CA');
INSERT INTO `area_codes` VALUES (606,1708,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (607,1709,'Canada - Newfoundland',NULL);
INSERT INTO `area_codes` VALUES (608,1712,'Iowa','US-IA');
INSERT INTO `area_codes` VALUES (609,1713,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (610,1714,'California','US-CA');
INSERT INTO `area_codes` VALUES (611,1715,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (612,1716,'New York','US-NY');
INSERT INTO `area_codes` VALUES (613,1717,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (614,1718,'New York','US-NY');
INSERT INTO `area_codes` VALUES (615,1719,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (616,1720,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (617,1721,'Sint Maarten',NULL);
INSERT INTO `area_codes` VALUES (618,1724,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (619,1725,'Nevada','US-NV');
INSERT INTO `area_codes` VALUES (620,1727,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (621,1731,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (622,1732,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (623,1734,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (624,1740,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (625,1747,'California','US-CA');
INSERT INTO `area_codes` VALUES (626,1754,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (627,1757,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (628,1760,'California','US-CA');
INSERT INTO `area_codes` VALUES (629,1762,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (630,1763,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (631,1765,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (632,1767,'Dominica',NULL);
INSERT INTO `area_codes` VALUES (633,1769,'Mississippi','US-MS');
INSERT INTO `area_codes` VALUES (634,1770,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (635,1772,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (636,1773,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (637,1774,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (638,1775,'Nevada','US-NV');
INSERT INTO `area_codes` VALUES (639,1778,'Canada - British Columbia',NULL);
INSERT INTO `area_codes` VALUES (640,1779,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (641,1780,'Canada - Alberta',NULL);
INSERT INTO `area_codes` VALUES (642,1781,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (643,1782,'Canada - Nova Scotia/PEI',NULL);
INSERT INTO `area_codes` VALUES (644,1784,'St. Vincent and the Grenadines',NULL);
INSERT INTO `area_codes` VALUES (645,1785,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (646,1786,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (647,1787,'Puerto Rico','US-PR');
INSERT INTO `area_codes` VALUES (648,1800,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (649,1801,'Utah','US-UT');
INSERT INTO `area_codes` VALUES (650,1802,'Vermont','US-VT');
INSERT INTO `area_codes` VALUES (651,1803,'South Carolina','US-SC');
INSERT INTO `area_codes` VALUES (652,1804,'Virginia','US-VA');
INSERT INTO `area_codes` VALUES (653,1805,'California','US-CA');
INSERT INTO `area_codes` VALUES (654,1806,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (655,1807,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (656,1808,'Hawaii','US-HI');
INSERT INTO `area_codes` VALUES (657,1809,'Dominican Republic',NULL);
INSERT INTO `area_codes` VALUES (658,1810,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (659,1812,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (660,1813,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (661,1814,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (662,1815,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (663,1816,'Missouri','US-MO');
INSERT INTO `area_codes` VALUES (664,1817,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (665,1818,'California','US-CA');
INSERT INTO `area_codes` VALUES (666,1819,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (667,1828,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (668,1829,'Dominican Republic',NULL);
INSERT INTO `area_codes` VALUES (669,1830,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (670,1831,'California','US-CA');
INSERT INTO `area_codes` VALUES (671,1832,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (672,1843,'South Carolina','US-SC');
INSERT INTO `area_codes` VALUES (673,1844,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (674,1845,'New York','US-NY');
INSERT INTO `area_codes` VALUES (675,1847,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (676,1848,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (677,1849,'Dominican Republic',NULL);
INSERT INTO `area_codes` VALUES (678,1850,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (679,1855,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (680,1856,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (681,1857,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (682,1858,'California','US-CA');
INSERT INTO `area_codes` VALUES (683,1859,'Kentucky','US-KY');
INSERT INTO `area_codes` VALUES (684,1860,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (685,1862,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (686,1863,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (687,1864,'South Carolina','US-SC');
INSERT INTO `area_codes` VALUES (688,1865,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (689,1866,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (690,1867,'\"Canada - NW Territories',NULL);
INSERT INTO `area_codes` VALUES (691,1868,'Trinidad & Tobago',NULL);
INSERT INTO `area_codes` VALUES (692,1869,'St. Kitts & Nevis',NULL);
INSERT INTO `area_codes` VALUES (693,1870,'Arkansas','US-AR');
INSERT INTO `area_codes` VALUES (694,1872,'Illinois','US-IL');
INSERT INTO `area_codes` VALUES (695,1873,'Canada - Quebec',NULL);
INSERT INTO `area_codes` VALUES (696,1876,'Jamaica',NULL);
INSERT INTO `area_codes` VALUES (697,1877,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (698,1878,'Pennsylvania','US-PA');
INSERT INTO `area_codes` VALUES (699,1888,'Toll free',NULL);
INSERT INTO `area_codes` VALUES (700,1901,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (701,1902,'Canada - Nova Scotia/PEI',NULL);
INSERT INTO `area_codes` VALUES (702,1903,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (703,1904,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (704,1905,'Canada - Ontario',NULL);
INSERT INTO `area_codes` VALUES (705,1906,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (706,1907,'Alaska','US-AK');
INSERT INTO `area_codes` VALUES (707,1908,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (708,1909,'California','US-CA');
INSERT INTO `area_codes` VALUES (709,1910,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (710,1912,'Georgia','US-GA');
INSERT INTO `area_codes` VALUES (711,1913,'Kansas','US-KS');
INSERT INTO `area_codes` VALUES (712,1914,'New York','US-NY');
INSERT INTO `area_codes` VALUES (713,1915,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (714,1916,'California','US-CA');
INSERT INTO `area_codes` VALUES (715,1917,'New York','US-NY');
INSERT INTO `area_codes` VALUES (716,1918,'Oklahoma','US-OK');
INSERT INTO `area_codes` VALUES (717,1919,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (718,1920,'Wisconsin','US-WI');
INSERT INTO `area_codes` VALUES (719,1925,'California','US-CA');
INSERT INTO `area_codes` VALUES (720,1928,'Arizona','US-AZ');
INSERT INTO `area_codes` VALUES (721,1929,'New York','US-NY');
INSERT INTO `area_codes` VALUES (722,1930,'Indiana','US-IN');
INSERT INTO `area_codes` VALUES (723,1931,'Tennessee','US-TN');
INSERT INTO `area_codes` VALUES (724,1936,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (725,1937,'Ohio','US-OH');
INSERT INTO `area_codes` VALUES (726,1938,'Alabama','US-AL');
INSERT INTO `area_codes` VALUES (727,1939,'Puerto Rico','US-PR');
INSERT INTO `area_codes` VALUES (728,1940,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (729,1941,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (730,1947,'Michigan','US-MI');
INSERT INTO `area_codes` VALUES (731,1949,'California','US-CA');
INSERT INTO `area_codes` VALUES (732,1951,'California','US-CA');
INSERT INTO `area_codes` VALUES (733,1952,'Minnesota','US-MN');
INSERT INTO `area_codes` VALUES (734,1954,'Florida','US-FL');
INSERT INTO `area_codes` VALUES (735,1956,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (736,1959,'Connecticut','US-CT');
INSERT INTO `area_codes` VALUES (737,1970,'Colorado','US-CO');
INSERT INTO `area_codes` VALUES (738,1971,'Oregon','US-OR');
INSERT INTO `area_codes` VALUES (739,1972,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (740,1973,'New Jersey','US-NJ');
INSERT INTO `area_codes` VALUES (741,1978,'Massachusetts','US-MA');
INSERT INTO `area_codes` VALUES (742,1979,'Texas','US-TX');
INSERT INTO `area_codes` VALUES (743,1980,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (744,1984,'North Carolina','US-NC');
INSERT INTO `area_codes` VALUES (745,1985,'Louisiana','US-LA');
INSERT INTO `area_codes` VALUES (746,1989,'Michigan','US-MI');
/*!40000 ALTER TABLE `area_codes` ENABLE KEYS */;
UNLOCK TABLES;
